[dataset]
dataset_path = "Data/train_data_26_100_3.npy"
batch_size = 1

[training]
causes_dim = 26
states_dim = [ 50, 15, 7]
output_dim = 3
tau_h = [ 10, 20, 40,]
alpha_x = 0.01
alpha_h = [ 0.05, 0.05, 0.05,]
iterations = 10000
save_directory = "Data/models/MultiMini/train/"
save_every_n_iteration = 100

[training.lr]
lr_o = 0.01
lr_h = [ 0.005, 0.005, 0.01,]
lr_c = 0.005

[onlineER]
model_type   = "pcrnn"
model_path   = "Data/models/MultiMini/train/seed1/iteration_10000/snapshot.pkl"
host         = "10.42.0.2"    
fps          = 20              
class_id     = 0             
use_feedback = true           
gripper_deg  = 10.0            
SequenceGeneration_save_directory = "Data/exp1_SequenceGeneration/MultiMini/"
alpha_x = 0.01
alpha_h = [ 0.05, 0.05, 0.05,]

[inferLetter]
alpha_x = 0.01
alpha_h = [ 0.05, 0.05, 1000.0,]